name: Run Camunda 7 Workflow

on:
  push:
    branches: [ dev ]

env:
  PROCESS_NAME: hello-world-process
  PROCESS_KEY: Process_1hadrig

jobs:
  camunda-run:
    runs-on: ubuntu-latest

    services:
      camunda:
        image: camunda/camunda-bpm-platform:run-latest
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl -f http://localhost:8080/camunda"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy BPMN model
        run: |
          ls --all
          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "deployment-name=hello-world-workflow" \
            -F "${PROCESS_NAME}.bpmn=@bpmn/${PROCESS_NAME}.bpmn" \
            http://localhost:8080/engine-rest/deployment/create

      - name: Start BPMN Process
        run: |
          curl -X POST http://localhost:8080/engine-rest/process-definition/key/${PROCESS_KEY}/start \
            -H "Content-Type: application/json" \
            -d '{
                  "variables": {
                    "inputVar": { "value": "example", "type": "String" }
                  }
                }'
